site_name: 'The Things Network'
theme_dir: 'theme'

pages:
    - Overview: 'index.md'
    - Common: 'common.md'
    - Router: 'router.md'
    - Broker: 'broker.md'
    - Network Server: 'networkserver.md'
    - Handler: 'handler.md'

extra:
    disqus: 'thethingsnetwork'
    meta:
        version: '1.0.0'
        status: 'draft'
        lead: 'Matthias Benkort'
        collaborators:
            - 'Johan Stokking'
            - 'Hylke Visser'
            - 'Thomas Telkamp'
